server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:JavaMissile/springcloud-config.git
          uri: https://github.com/JavaMissile/springcloud-config.git
          search-paths: springcloud-config
      label: master
      info: "master branch, springcloud-config/application-cc.yml version=1.1"
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
